CREATE DATABASE QuanLiSieuThi
GO


USE QuanLiSieuThi
GO

--Tạo bảng TaiKhoan
CREATE TABLE QUANLYTAIKHOAN(
	Taikhoan VARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(50) NOT NULL,
	HoVaTen NVARCHAR(50) NOT NULL,
	NgayTao DATE NOT NULL, 
	Quyen BIT
)
GO


insert into QUANLYTAIKHOAN
Values
('admin', 'adminadc', N'Nguyen Van A', '2024-05-20', 1),
('nv1', 'nv123', N'Tran Thi B', '2024-05-21', 0),
('nv2', 'nv234', N'Le Van C', '2024-05-22', 0);

--Tạo bảng NhaCungCap
CREATE TABLE NhaCungCap(
	MaNCC VARCHAR(50) NOT NULL PRIMARY KEY,
	TenNCC NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT INT NOT NULL
)
Go


--Tạo bảng SanPham
CREATE TABLE SanPham(
	MaSP VARCHAR(50) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	MaNCC VARCHAR(50) NOT NULL,
	GiaNhap FLOAT NOT NULL,
	GiaBan FLOAT NOT NULL,
	SoLuong INT NOT NULL,
	HSD DATE NOT NULL,
	DonViTinh NVARCHAR(20) NOT NULL
	FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
)
GO


CREATE TABLE HoaDon(
	MaHD VARCHAR (50) NOT NULL PRIMARY KEY,
	NgayBan DATETIME NOT NULL,
	TongTien FLOAT NOT NULL
)


CREATE TABLE ChiTietHD(
	MaHD VARCHAR (50) NOT NULL,
	MaSP VARCHAR(50) NOT NULL,
	SoLuong FLOAT NOT NULL,
	DonGia FLOAT NOT NULL,
	GiamGia FLOAT NOT NULL,
	ThanhTien FLOAT NOT NULL
	PRIMARY KEY(MaHD,MaSP)
	FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
	FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
)












